### ISSUE TITLE
Multilevel json 

### ISSUE THREAD

**Issue by nam-co** [hnhdigital-os/laravel-model-json#15]
Hi thanks for the package, I was wondering if this is possible:

I need to where/update a multilevel json columns, for example:
column name: items
items content: {"rows": [{"id": 1, "file": "herllo.jpg", "name": "vue clip maybe?", "video": "84_SwbPWjKo", "desc_en": "10", "desc_es": “change this"}, {"id": 2, "file": "herllo.jpg", "name": "hola como estas", "video": "", "desc_en": "10", "desc_es": “don’t change this"}]}

In this columns when user_id is x , I need to update "change this" to "", or where user_id = x and items->rows->id = 1 then update desc_es to ""

Appreciate any help

**Comment by therocis** [comment]
Thanks!

I believe it should be this:
```php
$user->items->rows[0]['desc_es'] = "";
$user->save();
```

or, if not, then try this:

```php
$user->items->rows[0]->desc_es = "";
```

Let me know how you go.

**Comment by nam-co** [comment]
Hi, Thanks for the response, for both I got "Indirect modification of overloaded property App\User_file::$items has no effect"

but I tried $file->items()->rows[0]['desc_es'] = "we did it";
and it worked thanks, but what happens if I don't know the row #, if it needs search "change this"/replace "to that"? for example:

$file = User_file::where(items()->rows['desc_es'], 'change this')->update(items()->rows['desc_es'], 'to that');
thanks, you package help me a lot

**Comment by therocis** [comment]
Ahh yes, sorry. Hadn't fully woken up - items is a method that returns an object.

There isn't any searching functionality available like you've shown but it's something I could look into building in. You might want to try the eloquent json querying instead which may get you the result you need?

**Comment by nam-co** [comment]
I tried but I couldn't get it working with rows, just the first level data

Maksuco.com

**Comment by therocis** [comment]
Try doing this:- (haven't tested)

where(DB::raw('items->"$.rows[*].desc_es"'), 'change this'))->update(DB::raw('items->"$.rows[*].desc_es"'), 'to that');
