### ISSUE TITLE
Call to undefined method

### ISSUE THREAD

**Issue by kiogo** [hnhdigital-os/laravel-model-json#19]
When storing, I'm getting the error: Call to undefined method App\Design::settings()

public function store(Request $request)
    {
        $design = new Design;
        $design->settings()->color = $request->color;
        $design->settings()->font = $request->font;
        $design->save();
    }

Update function works fine.
public function update(Request $request, Design $design)
    {
        $design->settings()->font = $request->font;
        $design->settings()->color = $request->color;
        $design->save();
    }

Please advise what I'm doing wrong. Thanks

**Comment by therocis** [comment]
May need to ititilise when creating a new model. Might need to update the docs to reflect this.

Can you try this:-
$design->inspectJson();

There is going to be an issue in L5.5 as they've moved having the methods in a trait. I'm going to get a change in L5.5 for some custom attribute types so this package will keep working.

**Comment by kiogo** [comment]
Adding $design->inspectJson() prevents the error, however the JSON column is stored with just "[]", and not the settings() values.

**Comment by therocis** [comment]
Okay. I'll have a look and see what's going on. What Laravel version are you using?

**Comment by kiogo** [comment]
L5.5, thanks
