### ISSUE TITLE
Magic method __call conflicts with other packages

### ISSUE THREAD

**Issue by azcoppen** [hnhdigital-os/laravel-model-json#20]
Trait method __call has not been applied, because there are collisions with other trait methods on App\Models\User. SImiliar issue to the setAttribute() ticket, but unable to override magic methods.

Any suggestions?

**Comment by therocis** [comment]
It's an issue for L5.5. haven't got a workaround yet. Hopefully be able to get a change in the Laravel core to facilitate this.
